export const keyMapping = {
    "TIPO IDENTIFICACION PASAJERO": "tipoIdePasajero",
    "IDENTIFICACION PASAJERO": "idePasajero",
    "NOMBRE DEL PASAJERO": "nombrePasajero",
    "NUMERO DE CONTRATO": "numeroContrato",
    "FECHA VIAJE": "fechaViaje",
    "CODIGO ORIGEN": "origen",
    "CODIGO DESTINO": "destino",
    "TIPO IDENTIFICACION PACIENTE": "tipoDocumento",
    "IDENTIFICACION PACIENTE": "numeroDocumento",
    "NOMBRE1": "nombre1",
    "NOMBRE2": "nombre2",
    "APELLIDO1": "apellido1",
    "APELLIDO2": "apellido2",
    "REGIMEN": "regimen",
    "TIPO AFILIACION": "tipoAfiliacion",
    "AUTORIZACION": "autorizacion",
    "ZONA": "zona",
    "CUPS": "tipoBono",
    "SEXO PACIENTE": "sexo",
    "TIPO BONO": "tipoBono",
    "CODIGO DEPARTAMENTO": "codDep",
    "CODIGO CIUDAD": "codCiu",
    "CANTIDAD": "tipoBono",
    "PRESCRIPCION": "prescripcion",
    "SERVICIO": "servicio",
    "TIPO VIAJE": "tipoViaje",
    "CREADO POR": "usuarioWeb",
    "MENSAJE DE ERROR":"error",
    "TELEFONO":"telefono",
    "CORREO":"correo"
  };

 export const keyMapping1 = {
    "tipoIdePasajero": "TIPO IDENTIFICACION PASAJERO",
    "idePasajero": "IDENTIFICACION PASAJERO",
    "nombrePasajero": "NOMBRE DEL PASAJERO",
    "numeroContrato": "NUMERO DE CONTRATO",
    "fechaViaje": "FECHA VIAJE",
    "origen": "CODIGO ORIGEN",
    "destino": "CODIGO DESTINO",
    "tipoDocumento": "TIPO IDENTIFICACION PACIENTE",
    "numeroDocumento": "IDENTIFICACION PACIENTE",
    "nombre1": "NOMBRE1",
    "nombre2": "NOMBRE2",
    "apellido1": "APELLIDO1",
    "apellido2": "APELLIDO2",
    "regimen": "REGIMEN",
    "tipoAfiliacion": "TIPO AFILIACION",
    "autorizacion": "AUTORIZACION",
    "zona": "ZONA",
    "tipoBono": "CANTIDAD", // Aquí, el último valor sobrescribe al anterior "CUPS"
    "sexo": "SEXO PACIENTE",
    "codDep": "CODIGO DEPARTAMENTO",
    "codCiu": "CODIGO CIUDAD",
    "prescripcion": "PRESCRIPCION",
    "servicio": "SERVICIO",
    "tipoViaje": "TIPO VIAJE",
    "numBono": "NUMERO BONO",
    "usuarioWeb": "CREADO POR",
    "error": "MENSAJE DE ERROR",
    "telefono":"TELEFONO",
    "correo":"CORREO"
  }